### ISSUE TITLE
Add Facebook Online Friend Tacker Project

### ISSUE THREAD

**Issue by bhamodi** [bhamodi/bhamodi.github.io#13]
Link to the:
- code
- blog post
- medium post

**Comment by edevena** [comment]
Hello, great idea :) it works fine but every time the app logs into Fb I receive a notification from Fb itself, even I save the browser. Maybe the cookies are deleted from one session to another so that Fb thinks it is a different browser everytime ?
A request, since Fb Login is veeery slow, can the app stay logged and update the csv ever ( say ) 15 minutes ?

**Comment by bhamodi** [comment]
Hey @edevena - thanks for the comment! I'll look into what I can do to make the script better. What you suggested sounds like a good approach. :)

**Comment by bhamodi** [comment]
This project has now been added to the `Projects` section.
